% enrich y^4    
% psi = {@(x,y) (0.5*(1 - y.^4) + 0.*x), @(x,y) 0.*y + 0.*x};
% gpsi = {@(x,y) 0.*y + 0.*x, @(x,y) (-2.*y.^3 + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};
% hpsi = {@(x,y) 0.*y + 0.*x, @(x,y) (-6.*y.^2 + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};
   

% enrich y^6    
% psi = {@(x,y) (0.5*(1 - y.^6) + 0.*x), @(x,y) 0.*y + 0.*x};
% gpsi = {@(x,y) 0.*y + 0.*x, @(x,y) (-3.*y.^5 + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};
% hpsi = {@(x,y) 0.*y + 0.*x, @(x,y) (-15.*y.^4 + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};   

% No enrichment on one half
% psi = {@(x,y) (y<=0).*(0.5*(1 - y.^2)) + (y>0).*0.5 + 0.*x, @(x,y) 0.*y + 0.*x};
% gpsi = {@(x,y) 0.*y + 0.*x, @(x,y) (y<=0).*(-1.*y)+ (y>0).*0 + 0.*x, ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};
% hpsi = {@(x,y) 0.*y + 0.*x, @(x,y) (y<=0).*(-1.)+ (y>0).*0 + 0.*y + 0.*x, ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};

% Blended enrichment
% En - Blend - normal .. - Blend - En
% N_en_form = 1;
% Ly = 2/Ey;
% ye = 1-Ly*N_en_form; % end of enrichment
% yb = 1-Ly*(N_en_form+1); % end of blending
% 
% blend = @(x,y) 0.*x + ...
%     (abs(y) >= (ye-eps)).*1 + ...
%     ((-(ye-eps) < y).*(y <= -(yb-eps))).*(y-(-yb))/((-ye)-(-yb)) + ...
%     + y.*0 + ...
%     (((ye-eps) > y).*(y >= (yb-eps))).*(y-(yb))/((ye)-(yb));
% dblend = @(x,y) 0.*x + ...
%     (abs(y) >= (ye-eps)).*0 + ...
%     ((-(ye-eps) < y).*(y <= -(yb-eps))).*1./((-ye)-(-yb)) + ...
%     + y.*0 + ...
%     (((ye-eps) > y).*(y >= (yb-eps))).*1./((ye)-(yb));
% hblend = @(x,y) 0.*x + ...
%     (abs(y) >= (ye-eps)).*0 + ...
%     ((-(ye-eps) < y).*(y <= -(yb-eps))).*0 + ...
%     + y.*0 + ...
%     (((ye-eps) > y).*(y >= (yb-eps))).*0;
% 
% % c1 = 1./(-ye^2-yb^2+2*ye*yb);
% % c2 = -2*ye*c1;
% % c3 = -(yb^2-2*yb*ye)*c1;
% % c1b = 1./(-(-ye)^2-(-yb)^2+2*(-ye)*(-yb));
% % c2b = -2*(-ye)*c1;
% % c3b = -((-yb)^2-2*(-yb)*(-ye))*c1;
% % blend = @(x,y) 0.*x + ...
% %     (abs(y) >= ye-eps).*1 + ...
% %     ((-(ye-eps) < y).*(y <= -(yb-eps))).*(c1b*y.^2+c2b*y+c3b) + ...
% %     + y.*0 + ...
% %     (((ye-eps) > y).*(y >= (yb-eps))).*(c1*y.^2+c2*y+c3);
% % 
% % dblend = @(x,y) 0.*x + ...
% %     (abs(y) >= (ye-eps)).*0 + ...
% %     ((-(ye-eps) < y).*(y <= -(yb-eps))).*(2*c1b*y+c2b) + ...
% %     + y.*0 + ...
% %     (((ye-eps) > y).*(y >= (yb-eps))).*(2*c1*y+c2);
% % 
% % hblend = @(x,y) 0.*x + ...
% %     (abs(y) >= (ye-eps)).*0 + ...
% %     ((-(ye-eps) < y).*(y <= -(yb-eps))).*2*c1b + ...
% %     + y.*0 + ...
% %     (((ye-eps) > y).*(y >= (yb-eps))).*2*c1;
% 
% en = @(x,y)(0.5*(1 - y.^2)) + 0.*x;
% den = @(x,y) (-1.*y + 0.*x);
% hen = @(x,y) (-1 - 0.*y + 0.*x);
% 
% psi = {@(x,y) blend(x,y).*en(x,y), @(x,y) 0.*y + 0.*x};
% gpsi = {@(x,y) 0.*y + 0.*x, ...
%         @(x,y) blend(x,y).*den(x,y) + dblend(x,y).*en(x,y), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};
% hpsi = {@(x,y) 0.*y + 0.*x, ...
%         @(x,y) blend(x,y).*hen(x,y) + 2*dblend(x,y).*den(x,y) + hblend(x,y).*en(x,y), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};

% Flat enrichment in middle
% Middle is higher than normal enrichment
% en_loc = 2/Ey+0.0001;
% psi = {@(x,y) ((1-abs(y))<=en_loc).*(0.5*(1 - y.^2) + 0.*x)+((1-abs(y))>en_loc).*0.5*(1-(1-2/Ey)^2), @(x,y) 0.*y + 0.*x};
% gpsi = {@(x,y) 0.*y + 0.*x, @(x,y) ((1-abs(y))<=en_loc).*(-1.*y + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};
% hpsi = {@(x,y) 0.*y + 0.*x, @(x,y) ((1-abs(y))<=en_loc).*(-1 - 0.*y + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};

% 0 enrichment in middle  
% Middle is slightly below normal enrichment
% en_loc = 2/Ey+0.000000001;
% psi = {@(x,y) ((1-abs(y))<=en_loc).*(0.5*(1 - y.^2) + 0.*x), @(x,y) 0.*y + 0.*x};
% gpsi = {@(x,y) 0.*y + 0.*x, @(x,y) ((1-abs(y))<=en_loc).*(-1.*y + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};
% hpsi = {@(x,y) 0.*y + 0.*x, @(x,y) ((1-abs(y))<=en_loc).*(-1 - 0.*y + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};

% % 0 enrichment in middle not full element
% Middle is slightly below normal enrichment
% [X,Y]=make_geom_channel(Ex,Ey,N);      % Geometry in local form
% en_loc = 1-abs(Y(1,end-1,1))+0.000000001;
% psi = {@(x,y) ((1-abs(y))<=en_loc).*(0.5*(1 - y.^2) + 0.*x), @(x,y) 0.*y + 0.*x};
% gpsi = {@(x,y) 0.*y + 0.*x, @(x,y) ((1-abs(y))<=en_loc).*(-1.*y + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};
% hpsi = {@(x,y) 0.*y + 0.*x, @(x,y) ((1-abs(y))<=en_loc).*(-1 - 0.*y + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};

% Flat enrichment in middle
% Middle is higher than normal enrichment
% en_loc = 2/Ey+0.0001;
% psi = {@(x,y) ((1-abs(y))<=en_loc).*(0.5*(1 - y.^2) + 0.*x)+((1-abs(y))>en_loc).*0.5*(1-(1-2/Ey)^2), @(x,y) 0.*y + 0.*x};
% gpsi = {@(x,y) 0.*y + 0.*x, @(x,y) ((1-abs(y))<=en_loc).*(-1.*y + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};
% hpsi = {@(x,y) 0.*y + 0.*x, @(x,y) ((1-abs(y))<=en_loc).*(-1 - 0.*y + 0.*x), ...
%         @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};

% 0 enrichment
% psi = {@(x,y) 0+0.*y + 0.*x, @(x,y) 0+0.*y + 0.*x;};
% gpsi = {@(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};
% hpsi = {@(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x, @(x,y) 0.*y + 0.*x};
